### ISSUE TITLE
Cannot launch Autoshop.exe

### ISSUE THREAD

**Issue by bwong320** [purpxd/E7AutoShop#7]
I followed set up instructions and didn't encounter any errors. When I try to launch autoshop.exe, a terminal flashes on my screen and closes. I tried opening it from cmd prompt and it gave me this error: " File "AutoShop.py", line 9, in <module>
FileNotFoundError"

**Comment by purpxd** [comment]
Hmm. It looks like that file might be missing when running the program. Can you post the entire error message?

**Comment by bwong320** [comment]
>  File "AutoShop.py", line 9, in <module>
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\Username\\build'
[4276] Failed to execute script 'AutoShop' due to unhandled exception!

**Comment by purpxd** [comment]
Are you able to locate the AutoShop.py file in the build folder? It should not be missing. If it is then there was a step that was missed during the installation.

**Comment by bwong320** [comment]
I see the autoShop.py file in the build folder. Is it case sensitive? Because in the error it shows AutoShop.py but when I checked the build folder it's autoShop.py

**Comment by bwong320** [comment]
I think the path it's looking for is incorrect. The error says ''C:\Users\Username\build'', but the E7AutoShop is installed in my download folder with path: "C:\Users\Username\Downloads\E7AutoShop"

**Comment by purpxd** [comment]
You can try to drag the build folder outside of the downloads directory then. I haven't seen this issue before. I'll try to replicate it and do an update

**Comment by bwong320** [comment]
I copied the build folder to the path the error was showing and now I get this error message when I try to run AutoShop.exe: 

> The system cannot find the path specified.
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

**Comment by purpxd** [comment]
Instead of running Autoshop.exe, go into the build folder and double click start-autoshop.bat if it exists there

**Comment by bwong320** [comment]
It's giving me the error Python was not found, but I have Python installed. I downloaded and installed it from the link in your install guide

**Comment by bwong320** [comment]
I installed Python via Microsoft Store and I ran InstallPackages again and this time it installed the packages properly. Previously it would run really quickly and it says the install completed. But now when I try running AutoShop.exe, it's expecting the build folder in C:\build now. I copied the folder there and I get this error:

> File "C:\build\autoShop.py", line 1, in <module>
    from PyQt5.QtWidgets import QApplication, QMainWindow, QTextEdit, QStatusBar, QTabWidget, QWidget, QPushButton, QVBoxLayout, QDialogButtonBox,  QTableWidget, QTableWidgetItem, QSpacerItem, QSizePolicy
ModuleNotFoundError: No module named 'PyQt5'

It seems like there's path issues with my install?

**Comment by purpxd** [comment]
I would remove everything and do a complete reinstall. It does seem like previously it wasn't running proper. Follow the steps exact and it should be working.

**Comment by bwong320** [comment]
Going to the correct path via cmd prompt and trying to run autoshop.exe I get this error:

> C:\Users\Username\Downloads\E7AutoShop>autoshop.exe
C:\Users\Username\Downloads\E7AutoShop\build\autoShop.py:606: SyntaxWarning: invalid escape sequence '\ '
  print("""
Traceback (most recent call last):
  File "C:\Users\Username\Downloads\E7AutoShop\build\autoShop.py", line 1, in <module>
    from PyQt5.QtWidgets import QApplication, QMainWindow, QTextEdit, QStatusBar, QTabWidget, QWidget, QPushButton, QVBoxLayout, QDialogButtonBox,  QTableWidget, QTableWidgetItem, QSpacerItem, QSizePolicy
ModuleNotFoundError: No module named 'PyQt5'

**Comment by purpxd** [comment]
It's possible that when running installpackages.exe that an error occured. PyQt5 should be there. You should let the thing run completely and do not exit it out until it is done. You will notice many lines going fast then it will stop for a while.

I did the installation on my laptop fresh. and was able to run the program successfully.

**Comment by bwong320** [comment]
I've redownloaded the install file in case it might have been corrupt, but doing a fresh install I'm still experiencing the same error. I let installpackages.exe run but the cmd prompt closes after it's finished so I can't see if it encountered any errors. Not sure what else to try, but thanks for trying to help debug the issue.
